version: '3.8'

x-base: &base
  image: chatwoot/chatwoot:v4.7.0
  env_file: .env
  volumes:
    - storage_data:/app/storage

services:
  rails:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: /app/start.sh
    # command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - storage_data:/app/storage
      - ./start.sh:/app/start.sh
    restart: always

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

volumes:
  storage_data:
